### ISSUE TITLE
ocabot: issue creating readme

### ISSUE THREAD

**Issue by GSLabIt** [OCA/oca-github-bot#172]
Anyone is experiencing issue on ocabot while creating readme? 

Error:
```
Traceback (most recent call last):
  File "/usr/local/bin/oca-gen-addon-readme", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/ocamt-readme/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/ocamt-readme/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/ocamt-readme/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/ocamt-readme/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/ocamt-readme/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/ocamt-readme/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PySocks!=1.5.7,<2.0,>=1.5.6; extra == "socks"' distribution was not found and is required by urllib3
```

## Module
The name of the module that has a bug.

## To Reproduce
**Affected versions**:

1.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by sbidoul** [comment]
@GSLabIt I have not noticed this. Can you provide more information on how to reproduce or a PR where you've seen the problem ?

**Comment by GSLabIt** [comment]
> @GSLabIt I have not noticed this. Can you provide more information on how to reproduce or a PR where you've seen the problem ?

It was related  urllib3, maybe new versions need `socks`; fixed in `Dockerfile`, see:

https://github.com/GSLabIt/oca-github-bot/blob/ooops-custom/Dockerfile#L31

**Comment by legalsylvain** [comment]
@GSLabIt could you make a PR ?
